### ISSUE TITLE
[Feature] Add support for specific kanban card color.

### ISSUE THREAD

**Issue by Quorafind** [chetachiezikeuzor/Yin-and-Yang-Theme#11]
After the newest update of Kanban [#181](https://github.com/mgmeyers/obsidian-kanban/pull/181), now we are allowed to modify specific card with specific tag by using css.

like:

```css
.kanban-plugin .has-tag-A .kanban-plugin__item-title-wrapper  {
  background: #fee9f4 !important; 
}

.kanban-plugin .has-tag-A .kanban-plugin__item-content-wrapper {
  padding: .3em .3em .3em .3em !important;
  border-radius: .025em !important;
  background: #fee9f4 !important; 
}

.kanban-plugin__item .has-tag-A {
  background: #fee9f4 !important; 
}
```

to change a card's color by using tag `A` .

So don't know if it is possible to add support to modify the css easily in style setting. If it is doable, please consider add this support.
