### ISSUE TITLE
Remove !important on .HyperMD-codeblock-bg

### ISSUE THREAD

**Issue by nothingislost** [chetachiezikeuzor/Yin-and-Yang-Theme#38]
If possible, please remove the !important declarations on code blocks. I'm working on a syntax highlighting plugin for code blocks and I'd like to avoid having to place my own !important declarations to override Yin&Yang.

.HyperMD-codeblock-bg {
    background-color: var(--pre-code) !important;
}

**Comment by nothingislost** [comment]
I'm getting around this like this for now but if it's possible, it'd be nice to not have to workaround the !importants

```css
body.unified-cm-highlighting[class*="theme-"] .HyperMD-codeblock-bg,
body.fallback-highlighting[class*="theme-"] .HyperMD-codeblock-bg {
  /* this is required to override YingYang's !important declaration */
  /* will remove as soon as it's removed from YinYang */
  --pre-code: var(--cm-background-color)
}
```
