### ISSUE TITLE
Compatibility with the Banners plugin

### ISSUE THREAD

**Issue by noatpad** [chetachiezikeuzor/Yin-and-Yang-Theme#54]
Hi there! I maintain the [Banners plugin](https://github.com/noatpad/obsidian-banners), basically a plugin that adds banner images to notes. I got an [issue](https://github.com/noatpad/obsidian-banners/issues/3) over on my repo where this theme is incompatible with it, and I thought I'd give it a look.

There are a couple of styling rules that override the banner wrapper for my plugin, specifically these ones:

https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/blob/5a5564033e0cbf72fb119598b24fe52cc18a6b81/obsidian.css#L3778-L3788

Messing around with the theme a tad, this can be resolved by either excluding those rules for `.obsidian-banner-wrapper`, with something like `:not()`, or adding a few extra rules into the theme that I tested with a snippet:

```css
.is-readable-line-width .markdown-preview-section > .obsidian-banner-wrapper {
  margin-top: calc(var(--banner-height) + 10px);
}

.markdown-embed .markdown-preview-section > .obsidian-banner-wrapper,
.is-readable-line-width .markdown-embed .markdown-preview-section > .obsidian-banner-wrapper {
	margin-top: calc(var(--banner-embed-height) + 10px);
}
```

I'm not sure which you prefer to implement, since both have their pros and cons, but yeah, if you can add compatibility to the plugin using either method, that'd be neat!
